### DISCUSSION TITLE
Tab-Leiste ausblenden

### DISCUSSION THREAD

**Discussion by Bernd9000** [Zefau/ioBroker.jarvis#2391] [Q&A] [answered]
Über CSS wollte ich für ein Dashboard die Tab-Leiste für eine jarvis Seite komplett ausblenden.
Mit folgendem Code funktioniert das auch.
Aber wie kann ich das auf nur eine jarvis Seite/Tab beschränken ?
Mir der davor gesetzten Selektion ".jarvis-page-xxxxxxxx-xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx" funktioniert es bei mir nicht
Geht das überhaupt?

.jarvis-header {
	display: none !important;
}
.q-page-container {
	padding-top: 0px !important;
}
.q-tab-panel {
       margin-top: 0px !important;
}

**Comment by Bernd9000** [comment]
-

**Comment by awsmfab** [comment]
Vermutlich bisschen spät für dich, aber brauchbar für den nächsten. Du könntest mit dem :has-Selektor prüfen ob ein Tab aktiv ist oder nicht.

Hiermit wird z.B. bei der Auswahl des bestimmten Tabs die Hintergrundfarbe vom Header weiß gefärbt.
```css
.jarvis-header:has(.q-tab--active.jarvis-tab-5d63d2d2-1284-4e85-8ad4-2c1ed78ad460) {
    background-color: red !important;
}
```

Für den Inhalt der Tabs brauchst du den Selektor nicht ob der Tab aktiv ist. Es wird immer nur ein Tab im DOM gerendert. Hier kannst du also direkt über den Selektor gehen.

```css
.q-tab-panel:has(> .jarvis-tab-5d63d2d2-1284-4e85-8ad4-2c1ed78ad460) {
    background-color: green !important;
}
```
