### ISSUE TITLE
Icon und Wert in secondary State über Script nicht möglich

### ISSUE THREAD

**Issue by stefgl** [Zefau/ioBroker.jarvis#2777]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- Jarvis PRO v3.2.0-beta.66

**Describe the bug / Beschreibe den Fehler**
Wie in der Anleitung unter https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/anzeigevariante/icon-statt-state-wert-pro beschrieben habe ich versucht ein icon mit wert für den Batterie-ladezustand meines Temperatursenors anzulegen.
Style für das Icon ist angelegt:
```css
.battery-med {
	display: inline-block;
	width: 1em;
	height: 1em;
	--svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath fill='%23000' d='M16.67 4H15V2H9v2H7.33A1.33 1.33 0 0 0 6 5.33v15.34C6 21.4 6.6 22 7.33 22h9.34A1.33 1.33 0 0 0 18 20.67V5.33C18 4.6 17.4 4 16.67 4'/%3E%3C/svg%3E");
	background-color: orange;
	-webkit-mask-image: var(--svg);
	mask-image: var(--svg);
	-webkit-mask-repeat: no-repeat;
	mask-repeat: no-repeat;
	-webkit-mask-size: 100% 100%;
	mask-size: 100% 100%;
}

.battery-ok {
	display: inline-block;
	width: 1em;
	height: 1em;
	--svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath fill='%23000' d='M16.67 4H15V2H9v2H7.33A1.33 1.33 0 0 0 6 5.33v15.34C6 21.4 6.6 22 7.33 22h9.34A1.33 1.33 0 0 0 18 20.67V5.33C18 4.6 17.4 4 16.67 4'/%3E%3C/svg%3E");
	background-color: green;
	-webkit-mask-image: var(--svg);
	mask-image: var(--svg);
	-webkit-mask-repeat: no-repeat;
	mask-repeat: no-repeat;
	-webkit-mask-size: 100% 100%;
	mask-size: 100% 100%;
}
```
Script sieht wie folgt aus:
```javascript
function valPlusIcon(val){
    let html = '';
    html+=  '<div><table>';
    html+=  '<tr>';
    html+=  '<td><span class="battery-med"> </span></td>';
    html+=  '<td>'+val+'</td>';
    html+=  '</tr>';
    html+=  '</table>';
    html+=  '</div>'
    return html;
}
```
Anzeigevariant für den DP sieht so aus:
```
{
  "<=20": "valPlusIcon({val})",
  ">20": "<span class='battery-ok'> </span>"
}
```
solange der Wert über 20 ist sehe ich das Battery-icon:
![image](https://github.com/user-attachments/assets/0bfa7fc5-710b-4da4-97f7-ab96cc0e3b8a)
Bei unter 20 sieht es dann so aus:
![image](https://github.com/user-attachments/assets/fcc772cb-0b47-446c-860d-0c2622540083)
diese Fehlermeldung wird angezeigt:
  ![image](https://github.com/user-attachments/assets/bc3731c6-df8c-4b9c-9ea9-1d479d686c1b)
und das steht in der Console:
  ![image](https://github.com/user-attachments/assets/2a4ed57c-76cf-4224-a6eb-3be5265404c9)

**Erwartetes Ergebnis**
Auf Basis der Anleitung sollte das orange Batteriesymbol zusammen mit dem Wert angezeigt werden.
